language: java
env:
  global:
    - secure: "JjzrgDBwGLPwSG6Ua8mvHc6JoLkwOs6mPlhvTd001WjDDpA+ylaUS4neQoaT\nhUBBhLYlm9Uaa2iMGZPdbTrsiWdhKzT0XOvyhZqo64Rt7skwnGyIe6MK9zZm\niumvDBVTk+spuI3ZxSEZFUA/7FFJEFwDgbjy9/9ceZo4LpFZG4U="
    - secure: "MoBPl4y2tbTvHi/QIcEZg9jxyGyfumzxOLKVK3c+JieFFYJF9AZuGuSidfiO\nwdRsE26IXWvyy7aUDhOZwlUOSOt7SXBx4QAUG6VHKsu2ncqZD5cEl0Ht3Va1\nbl4q8ovyd1dznMlz+nICrI6Omka1KTaLR9d+xyUAIm/b3P2yi/0="
    - secure: "YUc7JIZz6b1bpEyJ3VbG1fNqGvu4Zp4twI8xn1+4M14f/KwzxtYgq+/26HZ0\nO9nHrUIfQemj14Wtb1Jj4XzgMHT/i43Tn2vq96Xti1YpRG6OLDT0eZq3ci/U\nymjaMnKGDqi3t2wsnPDu3zTrykZIoXxqiA5SuHnBgVhx07cYZS4="
notifications:
  email:
    on_failure: change
jdk:
  - openjdk6
install: mvn -DskipTests=true -e install
script: mvn -e -Dskip.code.coverage=false -Dmaven.javadoc.skip=true -Dsource.skip=true verify
after_success: mvn sonar:sonar -Dsonar.sourceEncoding=UTF-8 -Dsonar.core.codeCoveragePlugin=jacoco -Dsonar.dynamicAnalysis=reuseReports -Dsonar.host.url=http://sonar.codereligion.com -Dsonar.jdbc.url=$SONAR_DB_URL -Dsonar.jdbc.username=$SONAR_DB_USER -Dsonar.jdbc.password=$SONAR_DB_PASSWORD
